name: Pull Request Tests

# Trigger workflow on pull request events
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
      - develop # Add any branches where PRs should trigger tests
    paths:
      - '**.ts' # Optional: Limit to specific file types or paths

jobs:
  run-tests:
    name: Run Tests on Pull Request
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify your project's Node.js version
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run lint-staged test cases
      - name: Run tests
        run: npm test -- --bail --verbose

      # Upload test artifacts (optional)
      - name: Upload test artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./test-results
